// TODO(yan): Values for margin, border and padding could be split into
// horizontal and vertical, or even per rect side, but only do that if it is
// actually useful as it otherwise takes a lot of space in the Ctrl struct.

pub struct Theme {
    pub button_border_color: u32,
    pub button_border_color_hovered: u32,
    pub button_border_color_active: u32,
    pub button_background_color: u32,
    pub button_background_color_hovered: u32,
    pub button_background_color_active: u32,
    pub button_text_color: u32,
    pub button_text_color_hovered: u32,
    pub button_text_color_active: u32,
    pub button_height: f32,
    pub button_margin: f32,
    pub button_border: f32,

    pub image_button_border_color: u32,
    pub image_button_border_color_hovered: u32,
    pub image_button_border_color_active: u32,
    pub image_button_background_color: u32,
    pub image_button_background_color_hovered: u32,
    pub image_button_background_color_active: u32,
    pub image_button_width: f32,
    pub image_button_height: f32,
    pub image_button_margin: f32,
    pub image_button_border: f32,

    pub checkbox_handle_color: u32,
    pub checkbox_handle_color_hovered: u32,
    pub checkbox_handle_color_active: u32,
    pub checkbox_text_color: u32,
    pub checkbox_text_color_hovered: u32,
    pub checkbox_text_color_active: u32,
    pub checkbox_width: f32,
    pub checkbox_height: f32,
    pub checkbox_margin: f32,
    pub checkbox_border: f32,

    pub text_border_color: u32,
    pub text_background_color: u32,
    pub text_text_color: u32,
    pub text_margin: f32,
    pub text_border: f32,
    pub text_padding: f32,

    pub text_tooltip_border_color: u32,
    pub text_tooltip_background_color: u32,
    pub text_tooltip_text_color: u32,
    pub text_tooltip_border: f32,
    pub text_tooltip_padding: f32,

    pub input_text_border_color: u32,
    pub input_text_border_color_hovered: u32,
    pub input_text_border_color_active: u32,
    pub input_text_background_color: u32,
    pub input_text_background_color_hovered: u32,
    pub input_text_background_color_active: u32,
    pub input_text_text_color: u32,
    pub input_text_text_color_hovered: u32,
    pub input_text_text_color_active: u32,
    pub input_text_height: f32,
    pub input_text_margin: f32,
    pub input_text_border: f32,

    pub drag_float_border_color: u32,
    pub drag_float_border_color_hovered: u32,
    pub drag_float_border_color_active: u32,
    pub drag_float_background_color: u32,
    pub drag_float_background_color_hovered: u32,
    pub drag_float_background_color_active: u32,
    pub drag_float_text_color: u32,
    pub drag_float_text_color_hovered: u32,
    pub drag_float_text_color_active: u32,
    pub drag_float_height: f32,
    pub drag_float_margin: f32,
    pub drag_float_border: f32,

    pub drag_int_border_color: u32,
    pub drag_int_border_color_hovered: u32,
    pub drag_int_border_color_active: u32,
    pub drag_int_background_color: u32,
    pub drag_int_background_color_hovered: u32,
    pub drag_int_background_color_active: u32,
    pub drag_int_text_color: u32,
    pub drag_int_text_color_hovered: u32,
    pub drag_int_text_color_active: u32,
    pub drag_int_height: f32,
    pub drag_int_margin: f32,
    pub drag_int_border: f32,

    pub dropdown_border_color: u32,
    pub dropdown_border_color_hovered: u32,
    pub dropdown_border_color_active: u32,
    pub dropdown_background_color: u32,
    pub dropdown_background_color_hovered: u32,
    pub dropdown_background_color_active: u32,
    pub dropdown_text_color: u32,
    pub dropdown_text_color_hovered: u32,
    pub dropdown_text_color_active: u32,
    pub dropdown_height: f32,
    pub dropdown_overlay_max_height: f32,
    pub dropdown_margin: f32,
    pub dropdown_border: f32,

    pub panel_border_color: u32,
    pub panel_background_color: u32,
    pub panel_border: f32,
    pub panel_padding: f32,

    pub window_border_color: u32,
    pub window_border_color_hovered: u32,
    pub window_background_color: u32,
    pub window_background_color_hovered: u32,
    pub window_border: f32,
    pub window_padding: f32,

    pub separator_color: u32,
    pub separator_height: f32,
    pub separator_margin: f32,
}

const TRANSPARENT: u32 = 0xffffff00;

const WINDOW_BACKGROUND_COLOR: u32 = 0x080808fa;
const WINDOW_BORDER_COLOR: u32 = 0x202020ff;

const BORDER_COLOR: u32 = 0x202020ff;
const BORDER_COLOR_HOVERED: u32 = 0x303030ff;
const BORDER_COLOR_ACTIVE: u32 = 0x505050ff;

const BACKGROUND_COLOR: u32 = 0;
const BACKGROUND_COLOR_HOVERED: u32 = 0x101010fa;
const BACKGROUND_COLOR_ACTIVE: u32 = 0x151515fa;

const TEXT_COLOR: u32 = 0xd0d0d0ff;

impl Theme {
    pub const DEFAULT: Self = Self {
        button_border_color: BORDER_COLOR,
        button_border_color_hovered: BORDER_COLOR_HOVERED,
        button_border_color_active: BORDER_COLOR_ACTIVE,
        button_background_color: BACKGROUND_COLOR,
        button_background_color_hovered: BACKGROUND_COLOR_HOVERED,
        button_background_color_active: BACKGROUND_COLOR_ACTIVE,
        button_text_color: TEXT_COLOR,
        button_text_color_hovered: TEXT_COLOR,
        button_text_color_active: TEXT_COLOR,
        button_height: 40.0,
        button_margin: 2.0,
        button_border: 1.0,

        image_button_border_color: BORDER_COLOR,
        image_button_border_color_hovered: BORDER_COLOR_HOVERED,
        image_button_border_color_active: BORDER_COLOR_ACTIVE,
        image_button_background_color: BACKGROUND_COLOR,
        image_button_background_color_hovered: BACKGROUND_COLOR_HOVERED,
        image_button_background_color_active: BACKGROUND_COLOR_ACTIVE,
        image_button_width: 40.0,
        image_button_height: 40.0,
        image_button_margin: 2.0,
        image_button_border: 1.0,

        checkbox_handle_color: 0xffffff50,
        checkbox_handle_color_hovered: 0xffffff70,
        checkbox_handle_color_active: 0xffffffa0,
        checkbox_text_color: TEXT_COLOR,
        checkbox_text_color_hovered: TEXT_COLOR,
        checkbox_text_color_active: TEXT_COLOR,
        checkbox_width: 250.0,
        checkbox_height: 40.0,
        checkbox_margin: 2.0,
        checkbox_border: 1.0,

        text_border_color: TRANSPARENT,
        text_background_color: TRANSPARENT,
        text_text_color: TEXT_COLOR,
        text_margin: 0.0,
        text_border: 0.0,
        text_padding: 10.0,

        text_tooltip_border_color: BORDER_COLOR,
        text_tooltip_background_color: WINDOW_BACKGROUND_COLOR,
        text_tooltip_text_color: TEXT_COLOR,
        text_tooltip_border: 1.0,
        text_tooltip_padding: 10.0,

        input_text_border_color: BORDER_COLOR,
        input_text_border_color_hovered: BORDER_COLOR_HOVERED,
        input_text_border_color_active: BORDER_COLOR_ACTIVE,
        input_text_background_color: TRANSPARENT,
        input_text_background_color_hovered: TRANSPARENT,
        input_text_background_color_active: TRANSPARENT,
        input_text_text_color: TEXT_COLOR,
        input_text_text_color_hovered: TEXT_COLOR,
        input_text_text_color_active: TEXT_COLOR,
        input_text_height: 40.0,
        input_text_margin: 2.0,
        input_text_border: 1.0,

        drag_float_border_color: BORDER_COLOR,
        drag_float_border_color_hovered: BORDER_COLOR_HOVERED,
        drag_float_border_color_active: BORDER_COLOR_ACTIVE,
        drag_float_background_color: TRANSPARENT,
        drag_float_background_color_hovered: TRANSPARENT,
        drag_float_background_color_active: TRANSPARENT,
        drag_float_text_color: TEXT_COLOR,
        drag_float_text_color_hovered: TEXT_COLOR,
        drag_float_text_color_active: TEXT_COLOR,
        drag_float_height: 40.0,
        drag_float_margin: 2.0,
        drag_float_border: 1.0,

        drag_int_border_color: BORDER_COLOR,
        drag_int_border_color_hovered: BORDER_COLOR_HOVERED,
        drag_int_border_color_active: BORDER_COLOR_ACTIVE,
        drag_int_background_color: TRANSPARENT,
        drag_int_background_color_hovered: TRANSPARENT,
        drag_int_background_color_active: TRANSPARENT,
        drag_int_text_color: TEXT_COLOR,
        drag_int_text_color_hovered: TEXT_COLOR,
        drag_int_text_color_active: TEXT_COLOR,
        drag_int_height: 40.0,
        drag_int_margin: 2.0,
        drag_int_border: 1.0,

        dropdown_border_color: BORDER_COLOR,
        dropdown_border_color_hovered: BORDER_COLOR_HOVERED,
        dropdown_border_color_active: BORDER_COLOR_ACTIVE,
        dropdown_background_color: BACKGROUND_COLOR,
        dropdown_background_color_hovered: BACKGROUND_COLOR_HOVERED,
        dropdown_background_color_active: BACKGROUND_COLOR_ACTIVE,
        dropdown_text_color: TEXT_COLOR,
        dropdown_text_color_hovered: TEXT_COLOR,
        dropdown_text_color_active: TEXT_COLOR,
        dropdown_height: 40.0,
        dropdown_overlay_max_height: 400.0,
        dropdown_margin: 2.0,
        dropdown_border: 1.0,

        panel_border_color: TRANSPARENT,
        panel_background_color: TRANSPARENT,
        panel_border: 0.0,
        panel_padding: 0.0,

        window_border_color: BORDER_COLOR,
        window_border_color_hovered: WINDOW_BORDER_COLOR,
        window_background_color: WINDOW_BACKGROUND_COLOR,
        window_background_color_hovered: WINDOW_BACKGROUND_COLOR,
        window_border: 1.0,
        window_padding: 5.0,

        separator_color: BORDER_COLOR,
        separator_height: 1.0,
        separator_margin: 8.0,
    };
}
